"groups":
- "name": "celery"
  "rules":
  - "alert": "CeleryTaskHighFailRate"
    "annotations":
      "dashboard_url": "https://grafana.com/d/celery-tasks-by-task-32s3/celery-tasks-by-task?&var-task={{ $labels.name }}"
      "description": "More than 5% tasks failed for the task {{ $labels.namespace }}/{{ $labels.name }} the past 10m."
      "summary": "Celery high task fail rate."
    "expr": |
      sum(
        increase(
          celery_task_failed_total{
            job=~"celery|celery-exporter",
            name!~"None"
          }[10m]
        )
      )  by (job, namespace, name)
      /
      sum(
        increase(
          celery_task_succeeded_total{
            job=~"celery|celery-exporter",
            name!~"None"
          }[10m]
        )
      )  by (job, namespace, name)
      * 100 > 5
    "labels":
      "severity": "warning"
  - "alert": "CeleryWorkerDown"
    "annotations":
      "description": "The Celery worker {{ $labels.hostname }} is offline."
      "summary": "A Celery worker is offline."
    "expr": |
      celery_worker_up{job=~"celery|celery-exporter"} == 0
    "for": "15m"
    "labels":
      "severity": "warning"
